path:
    attention_path : "data/aishell1/conformer/attention/text"
    attention_rescore: "data/aishell1/conformer/attention_rescoring/text"
    ctc_greedy_search : "data/aishell1/conformer/ctc_greedy_search/text"
    ctc_prefix_beam_search : "data/aishell1/conformer/ctc_prefix_beam_search/text"
text : "data/aishell1/label/text"
provider : aliyun
model : 
api_key : 
base_url : 
filter : 
    flag : false
    # '零','一','二','三','四','五','六','七','八','九','十',
    keyword : [ '馀','颠复','复盖','债劵' ]
    filterscp : data/aishell1/label/correct.scp
substitue:
    flag : false
    keyword :
        余 : 馀
        颠覆 : 颠复
        覆盖 : 复盖
        债券 : 债劵
        
shuffle : True
split_word: "输入:"
combination_num : 30
thread_num : 100
temperature : 0.2
max_repeat_times : 1
top_p : 0.4
format :
    changed_flag :  改
    keep_flag: 原
    flag_symbol: ["<",">"]
    output_symbol: ["[","]"]
prompt : ' 你会被提供语音识别后的短句,你的任务是在不引起更多错误的前提下纠正有把握纠正的同音或者读音相近的错别字，你必须给出推理的过程。

你应该按照下面的流程一步步的进行判断:(1)梳理句子的结构并且断句(2)判断句子是否有同音错别字(3)如果有错别字则将转化为有声调的汉语拼音(4)根据汉语拼音和上下文推断出候选的答案(5)选择上下文合理的答案,如果改变词的读音差别过大或者对答案没把握可以保持原句不变直接输出，答案用[]包裹,并且前面用<改>,<原>来表示是否修改

输入:他突然就干喔

断句：他 突然 就  干喔
推理:(1) "干喔" 有问题（(2)"干喔"的拼音是"gan1 wo3"(3)"gan1 wo3"的候选词有"干我"、"干窝","干呕"(4)最合适的选项为"干呕",但是"呕"和"喔"的读音分别为"ou3","wo",差别过大，不改变原句

结果:<原>[他突然就干喔]


输入:二零一八年还将举办第十四届世界短池游泳锦标赛

断句:二零一八年 还 将 举办 第十四届 世界 短池 游泳 锦标赛
推理:(1)句子没有语病，因此原样输出

结果:<原>[二零一八年还将举办第十四届世界短池游泳锦标赛]


输入:湖北荆州市安良百货公司事发首扶电梯已被关闭减修。
断句:湖北 荆州市 安良百货公司 事发 首扶电梯 已 被 关闭 减修。
推理:(1)句子有错别字，问题在"首扶","检修"(2)"首扶"的拼音是"shou3 fu2","减修"的拼音是"jian3 xiu1"(3)考虑上下文，"shou3 fu2"可能的候选词有"首次","手扶","首付",根据"jian3 xiu1"的拼音和上下文，三个候选答案可能是“检修”、“减修”、“建修”。(4)"手扶"、"检修"最符合上下文，并且"手扶"的读音为"shou3 fu2"和"首扶"一致，"检修"的读音为"jian3 xiu1"和"减修"一致，对答案有信心，因此纠正后的答案是："湖北荆州市安良百货公司事发手扶电梯已被关闭检修"，对答案持有信心，保留修改。

结果:<改>[湖北荆州市安良百货公司事发手扶电梯已被关闭检修]
'

